codons = [
    "ACA",
    "CCA",
    "GCA",
    "TCA",
    "AGA",
    "CGA",
    "GGA",
    "TGA",
    "ATA",
    "CTA",
    "GTA",
    "TTA",
    "AAC",
    "CAC",
    "GAC",
    "TAC",
    "AGC",
    "CGC",
    "GGC",
    "TGC",
    "ATC",
    "CTC",
    "GTC",
    "TTC",
    "AAG",
    "CAG",
    "GAG",
    "TAG",
    "ACG",
    "CCG",
    "GCG",
    "TCG",
    "ATG",
    "CTG",
    "GTG",
    "TTG",
    "AAT",
    "CAT",
    "GAT",
    "TAT",
    "ACT",
    "CCT",
    "GCT",
    "TCT",
    "AGT",
    "CGT",
    "GGT",
]

codon_dict = {"ACA": 0, "CCA": 1, "GCA": 2, "TCA": 3, "AGA": 4, "CGA": 5, "GGA": 6, "TGA": 7, "ATA": 8, "CTA": 9,
              "GTA": 10, "TTA": 11, "AAC": 12, "CAC": 13, "GAC": 14, "TAC": 15, "AGC": 16, "CGC": 17, "GGC": 18, 
              "TGC": 19, "ATC": 20, "CTC": 21, "GTC": 22, "TTC": 23, "AAG": 24, "CAG": 25, "GAG": 26, "TAG": 27, 
              "ACG": 28, "CCG": 29, "GCG": 30, "TCG": 31, "ATG": 32, "CTG": 33, "GTG": 34, "TTG": 35, "AAT": 36, 
              "CAT": 37, "GAT": 38, "TAT": 39, "ACT": 40, "CCT": 41, "GCT": 42, "TCT": 43, "AGT": 44, "CGT": 45, "GGT": 46}